name = "rawa-bitswap"

[defaults]
builder = "docker:go"
runner = "local:docker"

[builders."docker:go"]
enabled = true
build_base_image = "golang:1.19-buster"
# Log modfile to verify which version is used
dockerfile_extensions.pre_mod_download = 'RUN echo "Using go modfile: ${MODFILE}"'

[runners."local:docker"]
enabled = true

[runners."cluster:k8s"]
enabled = true

[[testcases]]
name = "rawa-test"
instances = { min = 3, max = 100, default = 10 }

  [testcases.params]
  debug = { type = "bool", desc = "show debug logs", default = false }
  timeout_secs = { type = "int", desc = "timeout for each individual run", unit = "seconds", default = 90 }
  run_count = { type = "int", desc = "number of iterations of the test", unit = "iteration", default = 1 }
  conn_per_node = { type = "int", desc = "creates connections to a number of peers at random", default = 2 }
  all_mode = { type = "bool", desc = "if enabled all nodes are both requestor and provider, if disabled there is 1 requestor and 1 provider", default = true }
  proxy_transition_prob = { type = "float", desc = "probability of transitioning into proxy phase instead of forwarding on each hop", default = 0.2 }
  unforwarded_search_time = { type = "int", desc = "time after which a node queries the content routing subsystem itself", unit = "seconds", default = 10 }
  forward_graph_degree = { type = "int", desc = "degree of the privacy-subgraph, 0 is the complete graph", default = 0 }
  closest_peerid_forward = { type = "bool", desc = "if enabled, selects the closest peer to a cid when forwarding, if not, selects randomly", default = false }
  first_spy = { type = "bool", desc = "if enabled the first-spy estimator is added to the network", default = false }
  forward_exploiter = { type = "int", desc = "determines the number of want-forward exploiter nodes that are added to the network", default = 0 }
